#TODOS LOS METODOS QUE EXISTEN PARA HACER COMENTARIOS EN PYTHON

#ESTE ES UN EJEMPLO DE COMENTARIO
print('COMETARIOS EN EL CODIGO')

"ESTE ES OTRO EJEMPLO DE COMO HACER COMENTARIOS"

'''HOLA
ESTO ES EJEMPLO DE COMO HACER
COMENTARIOS MULTILINEA
'''


